# Generated by Django 5.0.14 on 2025-09-13 20:02

from django.contrib.postgres.operations import TrigramExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
